- name: Get hostname and IP address of Alpine hosts
  hosts: my_servers
  vars:
    notify_discord_username: Semaphore
  gather_facts: yes
  tasks:
    - name: Display hostname and IP address
      debug:
        msg: "Hostname: {{ ansible_hostname }}, IP Address: {{ ansible_default_ipv4.address }}"

    # Send Discord message when reboot is required
    - name: Send Discord message
      community.general.discord:
        username: "{{ notify_discord_username }}"
      uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        body_format: json
        body: '{"content": "Reboot required on Hostname: {{ ansible_hostname }}, IP Address: {{ ansible_default_ipv4.address }}"}'
        headers:
          Content-Type: application/json
        status_code: 204
