- name: Get hostname and IP address of Alpine hosts
  vars:
    ansible_host_key_checking: false
    ansible_ssh_host_key_checking: false
  hosts: my_servers
  gather_facts: yes
  serial: 4
  tasks:
    - name: Display hostname and IP address
      debug:
        msg: "Hostname: {{ ansible_hostname }}, IP Address: {{ ansible_default_ipv4.address }}"

    - name: Pause for 2 seconds before starting again
      pause:
        seconds: 2        

    # Send Discord message when disk space is over 85%
    - name: Send Discord message
      uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        body_format: json
        body: '{"content": "Disk space on {{ ansible_hostname }} is above 85%!"}'
        headers:
          Content-Type: application/json
        status_code: [200, 204]
        validate_certs: yes
      delegate_to: localhost
      become: no
      when: disk_usage.stdout[:-1]|int > 85
