- hosts: my_servers
  vars:
    ansible_host_key_checking: false
    ansible_ssh_host_key_checking: false
  become: true
  tasks:
    - name: Print OS info
      ansible.builtin.package:
        name: apache2
